steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-App
    args:
      - --destination=gcr.io/$PROJECT_ID/angular:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/angular:latest
      - --context=./angular-tour-of-heroes
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud-Auth
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials primary-cluster --region us-central1 --project timing-terra

