apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/frontend-config: gke-frontendconfig
spec:
  defaultBackend:
    service:
      name: angular
      port:
        number: 443

