apiVersion: v1
kind: Service
metadata:
  name: angular
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: angular
  
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: {{ .Values.angular.containerPort }}
